### PR TITLE
Scala 2.13 cross compilation

### PR DESCRIPTION
**Pull request by pomadchin**
This PR adds Scala 2.13 cross compilation, sets it as the default Scala version and updates all dependencies.

Closes #271, #283, #290, #315, #316, #318, #319, #320, #322, #324, #325, #328, #329, #330

### CODE REVIEW

**Comment by ceedubs** [comment]
@pomadchin wow, thanks!

This is pretty much an abandoned project from me. It was probably fairly irresponsible of me to make a PR to frameless to use it in a test. Feel free to remove the dependency from frameless if this repo is ever a blocker; I won't be offended. Having said that, I appreciate your work on this and am happy to merge it if the build succeeds.

**Comment by pomadchin** [comment]
:D well, we can try to make it to 2.13 at least. And indeed it is a test dependency only; we'll see what's going to happen to it 🚀

**Comment by pomadchin** [comment]
🤦 don't know how it could compile locally.

**Comment by ceedubs** [comment]
🎉 build is 🟢

Thank you, @pomadchin!

**Comment by ceedubs** [comment]
@pomadchin should be available now: https://oss.sonatype.org/content/repositories/snapshots/net/ceedubs/irrec-parser_2.13/0.0.0+1-99fa3c91-SNAPSHOT/

**Comment by pomadchin** [comment]
Thank you! 🎉🎉🎉

**Pull request merged**
